### ISSUE TITLE
Complete name a lot of times is the directory path?

### ISSUE THREAD

**Issue by dragons4life** [lordmulder/mediainfo-gui#2]
I am wondering if this a bug or not, personally don't like this as this exposes the username made for your computer depending on the location.

**Comment by lordmulder** [comment]
Hello,

please explain what you are talking about (I have no idea). Maybe a screenshot could help to explain...

Regards.

**Comment by dragons4life** [comment]
"bug":  

General
Unique ID                                : 182868284484421787873121086008998324244 (0x89932686F4195754A25B9A1E08816814)
Complete name                            : X:\Movies\Seven Samurai\Seven.Samurai.1954.mkv

normal:

General
Unique ID                                : 182868284484421787873121086008998324244 (0x89932686F4195754A25B9A1E08816814)
Complete name                            : Seven.Samurai.1954.mkv

**Comment by lordmulder** [comment]
How do you define "normal"  :question:

MediaInfoXP, being a GUI front-end to [MediaInfo](https://github.com/MediaArea/MediaInfo), just shows the MediaInfo output **as-is**. And, as a matter of fact, the `Complete name` field shows the _full path_ (or URL) to the media file being analyzed.

I don't see how this "exposes" anything. First of all, the username will only appear in the path, if **(a)** _you_ decided to saved the media file in a path which contains your username, and **(b)** _you_ asked MediaInfo to analyze that specific file. Furthermore, MediaInfoXP just shows the inforamtion on your local computer. It is **not** like that info would be "leaked" anywhere. Thus I don't understand what is your concern...

But, in any case, if your request is to change the MediaInfo output, then that would be a [_MediaInfo change request_](https://github.com/MediaArea/MediaInfo/issues), **not** a MediaInfoXP (i.e. GUI front-end) thingy. Please don't shoot the messenger :smirk:

Regards.

**Comment by dragons4life** [comment]
I didn't define normal, I was asking if this wasn't normal.. lol.

a. you don't know if the info would be published anywhere
b. what If I do have the file were it exposes my username?
c. thanks I'll ask there.

**Comment by lordmulder** [comment]
> a. you don't know if the info would be published anywhere

Well, I _**do**_ know for sure that neither MediaInfoXP nor MediaInfo itself will "leak" the reported information anywhere. So, if that information gets "publish" in any kind of way, then because _you_ decided to do so. And, in that case, it would be your obligation to *review* the information that you decide to publish...

> b. what If I do have the file were it exposes my username?

Again, "it" (the aplication) does _not_ expose anything. And certainly _not_ without _your_ intervention.

It seems kind of silly to request that MediaInfo should "censor" its output, just because someone **_might_** mindlessly "copy and past" that output to Internet (or wherever). With the same argument, you could request that Windows Explorer should _not_ show the full path of the current directory, because eventually someone **_might_** might decide to take a screenshot of his Explorer window and post it on the Internet...

**Comment by dragons4life** [comment]
Leaks? Censoring? what are you saying?  All I said was "expose", and to fix this easily you can have the filename as a complete name. windows explorer is not use in the same fashion as mediainfo windows explorer (stick and stones), why are you making a bigger deal about this than me lol?

**Comment by lordmulder** [comment]
It still does **not** "expose" anything to anybody. It _does_ shows technical information to _**you**_. And _only_ to you. So, what _**you**_ do with that information – e.g. whether you decide to publish that information (and if so, what parts of it) – that is _**your**_ concern! No application in the world can make that decision for you...
