### ISSUE TITLE
Context menu error - "This file does not have an app associated with it for this action"

### ISSUE THREAD

**Issue by Adroid1dr** [lordmulder/mediainfo-gui#5]
Sorry if I'm doing something wrong, but the only way I can get this to work is by opening MediaInfoXP and dragging/dropping a media file. The right-click context menu doesn't work and gives me the error listed in the title. The regular MediaInfo right-click still works fine.
Full error message:
"This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

**Comment by lordmulder** [comment]
Not quite sure. Does seem to work for me 😄 

Please make sure that the `MediaInfoXP.exe` file still resides at the very same location where it was located when the shell associations were created. You can also try to toggle "Preferences" → "Enable shell integeration" from _enabled_ to _disabled_ and then back to _enabled_ again, so that the shell associations for MediaInfoXP will be re-created.

Regards.

**Comment by Adroid1dr** [comment]
> You can also try to toggle "Preferences" → "Enable shell integeration" in MediaInfoXP program from _enabled_ to _disabled_ and then back to _enabled_ again, so that the shell associations for MediaInfoXP will be re-created.

That seems to have fixed the problem, thank you.
