### ISSUE TITLE
Why Warning "Not all temporary files could be removed!"?

### ISSUE THREAD

**Issue by pstein** [lordmulder/mediainfo-gui#8]
Whenever I exit MI a warning popup appears:

Warning "Not all temporary files could be removed!"

Whats wrong?

**Comment by lordmulder** [comment]
Apparently, _**something**_ is "locking" the temporary files so that MediaInfo GUI was unable to delete them when exiting.

Most likely caused by _buggy_ "anti-virus" software 😩 

The "Find Handle" function of [Process Hacker](https://processhacker.sourceforge.io/nightly.php) can be useful to figure out which specific process is "locking" a particular file.

Also, the [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) could give more insight on what is actually going on, if you want to analyze it further...

(BTW: Does this happen every time when you exit the program or just sporadically?)
